### ISSUE TITLE
Question: How do you get this functioning?

### ISSUE THREAD

**Issue by Spodess** [dam0un/now-live#1]
I've never used webhooks before, but a friend who streams on Twitch wants to use this specifically (as you can customize the profile picture and whatnot). I was wondering where I can get started in setting this up.

**Comment by Damoun** [comment]
A webhook is just an url that you can request to send message to a channel on your discord.

If you go in the setting of one channel, you will find `Webhooks` in the menu. Click on the button to create one and you will get the url to use 🙂

**Comment by Spodess** [comment]
Yeah, I was more wondering how to use this webhook specifically, I was looking into some webhooks before, but more how to get this one specifically started up. Do I need any applications to host it? Or where am I putting Discord's webhook link?

Thanks for helping out by the way.

**Comment by Damoun** [comment]
I run manually in my browser at the start of the live https://dam0un.github.io/now-live/
This is not a bot that will send a message on discord automatically.

Maybe you are looking for this project https://nowlivebot.com (not mine).

**Comment by Spodess** [comment]
Oh, I see. Thanks!
